package com.mon.tutorial.repository;


import com.mon.tutorial.entity.User;
import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface UserRepository extends CrudRepository<User, Long> {
    // implementation will be automatically generated by Spring data
    // tutorial extends JpaRepository instead
}
